### ISSUE TITLE
Wrong position if use a custom component

### ISSUE THREAD

**Issue by eddiesigner** [mateuszRybczonek/vue-slick-popover#1]
Hi, first of all thanks for this component, it's pretty cool.

Now, I just found that if you trigger it from a custom component, the position is wrong. I managed to "solve it" by wrapping my custom component within a `span` element (I could use a `div` as well).

So, to be clear:

Wrong position:

```js
<my-custom-component ref="myPopover" @click="openPopover()" />
```

Good position:

```js
<span ref="myPopover" @click="openPopover()">
	<my-custom-component />
</span>
```

It would be nice if we can get rid of that extra element.

**Comment by mateuszRybczonek** [comment]
@eddiesigner, thanks for pointing that out.

popper.js requires the reference to be a DOM element, it was possible to trigger it with a Vue component, but the reference in that case should be `this.$refs. myPopover.$el` the `$el` is extracting the element from the component.

It should work now without a need of $el, please check (v0.1.2) and let me know if it works for you now.

**Comment by eddiesigner** [comment]
I see, thanks for your help, it works now 👍
